FROM nvidia/cuda:12.1.1-cudnn8-runtime-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Tokyo
RUN apt update -y && apt install -y python3 python3-pip pkg-config libcairo2-dev libgirepository1.0-dev libdbus-1-dev wget
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.10 1
RUN update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1

RUN pip install --upgrade pip
COPY ./requirements_gpu.txt ./requirements.txt
RUN pip install -r requirements.txt